version: "3.9"
services:

  web:
    image: ghcr.io/metastem/wikiless:latest
    environment:
      # see config.js.template for more settings
      DOMAIN: wikiless.example.org
      HTTP_ADDR: 0.0.0.0
      REDIS_URL: redis://redis
    ports:
      - 8080:8080
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    networks:
      - wikiless

  redis:
    image: "redis:alpine"
    container_name: redis
    user: nobody
    read_only: true
    tmpfs:
      - /data:size=10M,mode=0770,uid=65534,gid=65534,noexec,nosuid,nodev
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    networks:
      - wikiless

networks:
  wikiless:
